apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-mongo-hoursofoper
  namespace: monitoring
  labels:
    k8s-app: kafka-mongo-hoursofoper
spec:
  jobLabel: k8s-app
  endpoints:
  - path: /metrics
    port: web
    interval: 1s
    honorLabels: true
  selector:
    matchLabels:
      k8s-app: kafka-mongo-hoursofoper
  namespaceSelector:
    matchNames:
    - atd-core-platform