{
 "title": "kafka-mongo-hoursofoper-PythonService-Metrics",
 "tags": [ "python" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Data Stream Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Consumed Messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(consumed_messages_total{job=\"kafka-mongo-hoursofoper\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Consumed Messages",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(increase(consumed_messages_total{job=\"kafka-mongo-hoursofoper\"}[1m]))"
    }
   ]
  },
  {
   "title": "Kafka Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kafka_errors_total{job=\"kafka-mongo-hoursofoper\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Kafka Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(kafka_errors_total{job=\"kafka-mongo-hoursofoper\"}[1m]))"
    }
   ]
  },
  {
   "title": "MongoDB Latency",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mongodb_latency_sum{service=\"kafka-mongo-hoursofoper\"}[$__range]))/sum(increase(mongodb_latency_count{service=\"kafka-mongo-hoursofoper\"}[$__range]))"
    }
   ]
  },
  {
   "title": "MongoDB Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(mongodb_latency_sum{service=\"kafka-mongo-hoursofoper\"}[$__range]))/sum(increase(mongodb_latency_count{service=\"kafka-mongo-hoursofoper\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Processed Messages",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(processed_messages_total{job=\"kafka-mongo-hoursofoper\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Processed Messages",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum(increase(processed_messages_total{job=\"kafka-mongo-hoursofoper\"}[1m]))"
    }
   ]
  },
  {
   "title": "Processing Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(processing_errors_total{job=\"kafka-mongo-hoursofoper\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Processing Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 6 },
   "targets": [
    {
     "expr": "sum(increase(processing_errors_total{job=\"kafka-mongo-hoursofoper\"}[1m]))"
    }
   ]
  },
  {
   "title": "Total Inserts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(records_inserted_total{job=\"kafka-mongo-hoursofoper\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Updates",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(records_updated_total{job=\"kafka-mongo-hoursofoper\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Total Deletes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(records_deleted_total{job=\"kafka-mongo-hoursofoper\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"atd-core-platform\", container=\"kafka-mongo-hoursofoper\"}[1m]))"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{namespace=\"atd-core-platform\", container=\"kafka-mongo-hoursofoper\"}[1m])) by(pod)"
    }
   ]
  },
  {
   "title": "Pod Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=\"atd-core-platform\", container=\"kafka-mongo-hoursofoper\"})"
    }
   ]
  },
  {
   "title": "Current Lag",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "current_lag{service=\"kafka-mongo-hoursofoper\"}"
    }
   ]
  },
  {
   "title": "Consumer Lag",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 3, "y": 11 },
   "targets": [
    {
     "expr": "max(current_lag{service=\"kafka-mongo-hoursofoper\"})"
    }
   ]
  },
  {
   "title": "MongoDB Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(mongodb_errors_total{job=\"kafka-mongo-hoursofoper\"}[$__range]))"
    }
   ]
  },
  {
   "title": "MongoDB Errors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 3, "x": 11, "y": 11 },
   "targets": [
    {
     "expr": "sum(increase(mongodb_errors_total{job=\"kafka-mongo-hoursofoper\"}[1m]))"
    }
   ]
  },
  { "title": "Resource Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"atd-core-platform\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"atd-core-platform\", workload=\"kafka-mongo-hoursofoper\"}\n) by (pod)\n",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"atd-core-platform\", pod=~\"kafka-mongo-hoursofoper.*\", resource=\"cpu\"}\n",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "CPU Percentage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"atd-core-platform\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"atd-core-platform\", workload=\"kafka-mongo-hoursofoper\"}\n) by (pod)\n/sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"atd-core-platform\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"atd-core-platform\", workload=\"kafka-mongo-hoursofoper\"}\n) by (pod)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"atd-core-platform\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"atd-core-platform\", workload=\"kafka-mongo-hoursofoper\"}\n) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{job=\"kube-state-metrics\", namespace=\"atd-core-platform\", pod=~\"kafka-mongo-hoursofoper.*\", resource=\"memory\"}",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory Percentage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"atd-core-platform\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"atd-core-platform\", workload=\"kafka-mongo-hoursofoper\"}\n) by (pod)\n/sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"atd-core-platform\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"atd-core-platform\", workload=\"kafka-mongo-hoursofoper\"}\n) by (pod)"
    }
   ]
  },
  {
   "title": "Recieve Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(sum(irate(container_network_receive_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"atd-core-platform\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"atd-core-platform\", workload=~\"kafka-mongo-hoursofoper\"}) by (pod))\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"atd-core-platform\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"atd-core-platform\", workload=\"kafka-mongo-hoursofoper\"}\n) by (pod)"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"atd-core-platform\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"atd-core-platform\", workload=\"kafka-mongo-hoursofoper\"}\n) by (pod)"
    },
    {
     "expr": "sum(\n    node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"atd-core-platform\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"atd-core-platform\", workload=\"kafka-mongo-hoursofoper\"}\n) by (pod)\n/sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"atd-core-platform\", resource=\"cpu\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"atd-core-platform\", workload=\"kafka-mongo-hoursofoper\"}\n) by (pod)"
    }
   ]
  },
  {
   "title": "Memory Quota",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 24 },
   "targets": [
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"atd-core-platform\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"atd-core-platform\", workload=\"kafka-mongo-hoursofoper\"}\n) by (pod)"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"atd-core-platform\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"atd-core-platform\", workload=\"kafka-mongo-hoursofoper\"}\n) by (pod)"
    },
    {
     "expr": "sum(\n    container_memory_working_set_bytes{namespace=\"atd-core-platform\", container!=\"\", image!=\"\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"atd-core-platform\", workload=\"kafka-mongo-hoursofoper\"}\n) by (pod)\n/sum(\n    kube_pod_container_resource_requests{job=\"kube-state-metrics\", namespace=\"atd-core-platform\", resource=\"memory\"}\n  * on(namespace,pod)\n    group_left(workload, workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"atd-core-platform\", workload=\"kafka-mongo-hoursofoper\"}\n) by (pod)"
    }
   ]
  },
  {
   "title": "Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "(sum(irate(container_network_transmit_bytes_total{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"atd-core-platform\"}[$__rate_interval])\n* on (namespace,pod)\ngroup_left(workload,workload_type) namespace_workload_pod:kube_pod_owner:relabel{namespace=\"atd-core-platform\", workload=~\"kafka-mongo-hoursofoper\"}) by (pod))\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{job=\"atd-core-platform/kafka-mongo-hoursofoper\"}"
    }
   ]
  }
 ]
}